### ISSUE TITLE
Question about image size

### ISSUE THREAD

**Issue by yjhong89** [choyingw/SynergyNet#1]
Dear author, 

I am YJHong and thanks for sharing your great work!

I would like to use your work for extracting facial landmarks and have 2 questions.

1. Is there any face detection module for extracting facial landmarks ?
For example 3D-FAN (Face Alignment Network), it detects faces in first and extract landmarks from cropped image.
While looking "benchmark.py" code, it seems there is no particular face detection module. Am I correct ?

2. If question 1 is correct, how do I crop my own images like AFLW2000-3D_crop dataset you provided ?
All images in AFLW2000-3D_crop have same (120, 120) size and they looks like all of them have been face-centered cropped with some kind of preprocessing.

3. Image input size is fixed at (120, 120) for SynergyNet ?
If I want to use SynergyNet, do I should crop images to (120, 120) ? 
Or is it able to just pass raw images to SynergyNet and get landmarks of them ?

Again, thanks for your work!

Best regards,
YJHong.

**Comment by choyingw** [comment]
The AFLW2000-3D are cropped based on 3DDFA (https://github.com/cleardusk/3DDFA/tree/master/test.configs). This benchmark script is for validating our performance. 

We do include a face detector for processing in-the-wild images and will release that part of codes recently.
