### ISSUE TITLE
Missing 3dmm_data

### ISSUE THREAD

**Issue by quqixun** [choyingw/SynergyNet#2]
Thanks for your work.
Could you upload 3dmm_data dir?
Or the link of 3dmm data for downloading.

**Comment by choyingw** [comment]
The download link is in readme Evaluation - step 4 (https://drive.google.com/file/d/1SQsMhvAmpD1O8Hm0yEGom0C0rXtA0qs8/view).

**Comment by quqixun** [comment]
Thanks.
I should read readme more carefully.
