### ISSUE TITLE
evaluation of AFLW dataset

### ISSUE THREAD

**Issue by yjwnet9** [choyingw/SynergyNet#21]
<img width="433" alt="캡처" src="https://user-images.githubusercontent.com/109531833/179649365-eef3613d-92be-4e14-950e-26a978c978e9.PNG">
<img width="222" alt="캡처" src="https://user-images.githubusercontent.com/109531833/179649481-0ff9e26c-5312-46db-8dd2-2af16deb46ed.PNG">
Face alignment evaluation result of AFLW in the paper and my evaluation result are different.

Could you provide the evaluation code of AFLW dataset?

**Comment by choyingw** [comment]
[			self.keypoints = _load(osp.join(d, 'keypoints_sim.npy'))](https://github.com/choyingw/SynergyNet/blob/d34e4afd6adbb9d5339366e3e74cde709d5895ae/utils/params.py#L13)

![facial_landmarks_68markup](https://user-images.githubusercontent.com/43560997/208231281-2cf563c8-c53f-44cd-b504-deb57f61ab71.jpg)

![Screenshot from 2022-12-16 23-36-44](https://user-images.githubusercontent.com/43560997/208231305-e2ebeb3c-9b99-4732-8f28-ea93fec40014.png)
