### ISSUE TITLE
Problem compiling FaceBoxes

### ISSUE THREAD

**Issue by pepeballesterostel** [choyingw/SynergyNet#29]
After trying a couple of times, I find impossible to correctly compile the file _./build_cpu_nms.sh_. The error is:
```
cl : Command line error D8021 : **invalid numeric argument '/Wno-cpp'**
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```
I am not sure if this could be related to the operating system. I am running the code in **Visual Studio Code** on **Windows 11**. 

Looking after the error I found [this](https://github.com/cocodataset/cocoapi/issues/51). So I changed in _build.py_ inside _FaceBoxes/utils_ the line of code 47:
from
`extra_compile_args=["-Wno-cpp", "-Wno-unused-function"]
`to 
`extra_compile_args={'gcc': ['/Qstd=c99']}
`
After running this, I get the following warnings:
```
cl : Command line warning D9024 : unrecognized source file type 'gcc', object file assumed
cl : Command line warning D9027 : source file 'gcc' ignored
```
From where I assume that is basically not compiling the extra modules, but ignoring it. So, it does not show and error, but as expected, the code does not work. The error raises in _FaceBoxes\utils\nms_wrapper.py_ :
```
  File "nms\cpu_nms.pyx", line 25, in nms.cpu_nms.cpu_nms
ValueError: Buffer dtype mismatch, expected 'int_t' but got 'long long'
```
I also tried commenting line 47 - in build.py inside _FaceBoxes/utils_ - and uncommenting line 46, which raises the same error.

Any ideas how to solve this?
Many thanks.

**Comment by RichestYoo** [comment]
Just the same for me

**Comment by pepeballesterostel** [comment]
@RichestYoo I am pretty sure I have solved the problem adding this line of code:
`os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
`
Let me know

**Comment by RichestYoo** [comment]
@pepeballesterostel 
Where am I supposed to put that line in? 

I put that in FaceBoxes/utils/build.py like the following failed:
    ext_modules = [
        Extension(
            "nms.cpu_nms",
            ["nms/cpu_nms.pyx"],
            extra_compile_args=["-Wno-cpp", "-Wno-unused-function"],
            include_dirs=[numpy_include],
            os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
        )
    ]

And "TRUE", instead of True seems to say that it's not a python source.

**Comment by pepeballesterostel** [comment]
Put it in the main script that you are running,  for example [singleImage.py](https://github.com/choyingw/SynergyNet/blob/main/singleImage.py). I added it after the imports.
The command basically tells python that is ok to have multiple copies of the library MKL loaded into memory, which seems to be the initial compiling error.

**Comment by pepeballesterostel** [comment]
@RichestYoo 
Put it in the main script that you are running, for example [singleImage.py](https://github.com/choyingw/SynergyNet/blob/main/singleImage.py). I added it after the imports.
The command basically tells python that is ok to have multiple copies of the library MKL loaded into memory, which seems to be the initial compiling error.

**Comment by RichestYoo** [comment]
@pepeballesterostel 
Thank you for your help, but it didn't work out for me.
After first failure, I put that in the environment variable as "os.environ" is bringing/setting PC's environment variable, 
and tried again, but same error message came up.

**Comment by pepeballesterostel** [comment]
@RichestYoo 
Try changing your code from [ build.py](https://github.com/choyingw/SynergyNet/blob/main/FaceBoxes/utils/build.py) to this code:
ext_modules = [
    Extension(
        "nms.cpu_nms",
        ["nms/cpu_nms.pyx"],
        #extra_compile_args={'gcc': ["-Wno-cpp", "-Wno-unused-function"]},
        extra_compile_args=['std=c99'],
        include_dirs=[numpy_include]
    )
]
Does this work for you?

**Comment by RichestYoo** [comment]
@pepeballesterostel 
With that, I passed the build failure you wrote at the beginning but now I'm at this "int_t" vs. 'long long' stuff...

**Comment by RichestYoo** [comment]
@pepeballesterostel 
Sure. Thank you for your sincere helps.

**Comment by HeChengHui** [comment]
@RichestYoo 
did you managed to get it working? 

i have added `extra_compile_args=['std=c99'],` to FaceBoxes build.py and `os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE" ` to singleImage.py butstuck at `'int_t' but got 'long long'` problem.

**Comment by RichestYoo** [comment]
Thank you for your help, but I'm transferred to another job and is not working on this any more.
