### ISSUE TITLE
Training code + How can I render for 3D face output

### ISSUE THREAD

**Issue by ofirkris** [choyingw/SynergyNet#3]
Hello, amazing work!
Can you please share the training code + 3D face weights and inference code?

**Comment by choyingw** [comment]
We will soon give an update on the other part code release.

**Comment by ofirkris** [comment]
Thanks, any expected timeline?

**Comment by choyingw** [comment]
The training codes are released. We'll release the rest part of codes this week.

**Comment by choyingw** [comment]
The full codes are also released. Thanks!

**Comment by lhyfst** [comment]
Kudos!
