### ISSUE TITLE
Robustness for faces in the wild

### ISSUE THREAD

**Issue by zhengkw18** [choyingw/SynergyNet#4]
![test2](https://user-images.githubusercontent.com/49091153/143218952-41ff6638-f951-4a68-8421-8b52de3a9613.jpg)
![pncc](https://user-images.githubusercontent.com/49091153/143218968-bbe202a6-5148-4107-be9c-20a23ef09b29.jpg)
I use an image in dataset VoxCeleb1 and render the pncc (projected normalized coordinate code) corresponding to the 3DMM fitted by your pretrained model. I think there is much error in its matching result.

For some other angles, the result is ok
![test1](https://user-images.githubusercontent.com/49091153/143219443-0d34c9fe-c611-4c0b-99da-5fc5ad868fe8.jpg)
![pncc2](https://user-images.githubusercontent.com/49091153/143219455-e2ae94d0-83ae-4a58-a910-8253c7beeb5b.jpg)

**Comment by choyingw** [comment]
Thanks for your sharing. In the first example, the performance should be optimal if the face is center-cropped. We'll release the single-image inference demonstration recently.

**Comment by choyingw** [comment]
The full codes are released.
