### ISSUE TITLE
This training size is less than 44G (train_aug_120x120.zip)

### ISSUE THREAD

**Issue by lhyfst** [choyingw/SynergyNet#5]
Hi, 
Thanks for sharing your amazing code!

I am trying to run your training code. In Training 2, you mentioned 
"Download training data from [3DDFA]: train_aug_120x120.zip and extract the zip file under the root folder (This training size is about 44G)."

However, when I open 3DDFA, I only find a train_aug_120x120.zip with 2.15G. After extracting, it only has 2.8G, which is far less than 44G.

I am wondering, am I missing some information to get the whole dataset?

![0e72a3e795fcfaf676b1543f2fd6ac4](https://user-images.githubusercontent.com/29816816/143734218-75f5cf74-a360-47cd-b1d8-8b882efeeb8e.png)

**Comment by choyingw** [comment]
Yes, we use this training data. It should contain about 680K images.
